version: 2.1

executors:
  ubuntu-docker:
    docker:
      - image: circleci/python:3.8.1

commands:
  build:
    steps:
      - run: echo 'Hello World'

jobs:
  first-job:
    executor: ubuntu-docker
    steps:
      - build


workflows:
  deploy-to-digital-ocean:
    jobs:
      - first-job
