version: 2.1

executors:
  ubuntu-docker:
    docker:
      - image: abrahamvarricatt/ubuntu-ansible-toolbox:latest

commands:
  # install-ansible:
  #   steps:
  #     - run: apt-get update
  #     - run: apt-get -y install ansible git python3
  #     - run: ansible --version
  
  run-ansible:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6f:c7:bf:67:64:7b:5c:e3:4c:4f:b2:0f:5d:dd:a7:09"
      - checkout  
      - run: ./run_ansible.sh

jobs:
  deployment-job:
    executor: ubuntu-docker
    steps:
      - install-ansible
      - run-ansible


workflows:
  deployment-workflow:
    jobs:
      - deployment-job
