version: 2.1

executors:
  ubuntu-docker:
    docker:
      - image: ubuntu:bionic-20200403

commands:
  build:
    steps:
      - run: echo 'Hello World'
      - run: apt-get update
      - run: apt-get install ansible
      - run: ansible --version

jobs:
  deployment-job:
    executor: ubuntu-docker
    steps:
      - build


workflows:
  deployment-workflow:
    jobs:
      - deployment-job
