---

  - name: Create symlink to webapp source folder
    file:
      state: link
      src: /home/{{ webapp_user }}/droplet_provisioner/dotNetWebApp
      dest: /var/www/movie-app

  - name: Updating appsettings.json from template
    template:
      src: appsettings.json.j2
      dest: /var/www/movie-app/appsettings.json
      owner: "{{ webapp_user }}"
      group: "{{ webapp_user }}"
      mode: u=rw,g=rw,o=r

  - name: Update database with tables
    become: yes
    become_user: "{{ webapp_user }}"
    shell: dotnet ef database update
    args:
      chdir: /var/www/movie-app

  - name: Build project
    become: yes
    become_user: "{{ webapp_user }}"
    shell: dotnet build
    args:
      chdir: /var/www/movie-app

  - name: Publish dotNet project
    become: yes
    become_user: "{{ webapp_user }}"
    shell: dotnet publish
    args:
      chdir: /var/www/movie-app
    notify:
      - Restart dotNetWebApp
      - Restart nginx

  - name: install dotNetWebApp systemd unit file
    template: 
      src: webapp.service.j2 
      dest: /etc/systemd/system/webapp.service
    notify:
      - Restart dotNetWebApp

  - name: install nginx configuration file for dotnet_webapp
    template: 
      src: dotnet_webapp.j2 
      dest: /etc/nginx/sites-available/dotnet_webapp
    notify:
      - Restart nginx

  - name: Activate dotnet_webapp on nginx via symbolic link
    file:
      state: link
      src: /etc/nginx/sites-available/dotnet_webapp
      dest: /etc/nginx/sites-enabled/dotnet_webapp
    notify:
      - Restart nginx      

  - name: Delete default nginx config
    file:
      state: absent
      path: /etc/nginx/sites-enabled/default
    notify:
      - Restart nginx
